server:
  port: 5711

spring:
  datasource:
    url: jdbc:mysql://rm-bp1a6r518081j0p7zuo.mysql.rds.aliyuncs.com:3306/rmy?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&serverTimezone=GMT%2B8
    username: root
    password: Rmy12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  rabbitmq:
    #    host: 101.35.107.55
    host: 120.26.38.27
    port: 5672
    #    username: tjk
    username: rmy
    password: 123456
#    virtual-host: /rmy
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: false
  mapper-locations: classpath*:dao/*.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 逻辑未删除
      logic-not-delete-value: 0
      # 逻辑已删除
      logic-delete-value: 1

oss:
  # oss 上传回调地址
  # 本地测试推荐工具 ngrok 将本地服务暴露在互联网中
  bucket: test-rmy
  endpoint: https://oss-cn-beijing.aliyuncs.com
  access-id: LTAI5t6VUDRTVkWzG2Ck5hCQ
  access-key: oSS7Ga4DlX0EuOAXQ9a6Dx2AvPmpUW
  host: https://test-rmy.oss-cn-beijing.aliyuncs.com
  callback-url: http://106.14.97.123/examination-admin-api/token/callback

rabbit:
  queues: rmy.queue.first,rmy.queue.send,rmy.queue.connect,rmy.queue.upgrade,rmy.queue.checkData,rmy.queue.reagentSurplus,rmy.queue.reagentMainCurve,rmy.queue.CaliData,rmy.queue.consumables,rmy.queue.fault,rmy.queue.qualityData,rmy.queue.GPSInfo,ProjectInfo
  exchange: rmyDirectExchange
  topicbindqueue:
    /upgrade: rmy.queue.upgrade
    /tjk: rmy.queue.first
    checkData: rmy.queue.checkData
    reagentSurplus: rmy.queue.reagentSurplus
    reagentMainCurve: rmy.queue.reagentMainCurve
    CaliData: rmy.queue.CaliData
    consumables: rmy.queue.consumables
    fault: rmy.queue.fault
    qualityData: rmy.queue.qualityData
    GPSInfo: rmy.queue.GPSInfo
    ProjectInfo: rmy.queue.ProjectInfo


mqtt:
  #  address: tcp://101.35.107.55:1883
  address: tcp://120.26.38.27:1883
  clientId: host_tjk_fau
  userName: admin
  password: public
  defaultTopic: /tjk,$SYS/brokers/+/clients/+/connected,$SYS/brokers/+/clients/+/disconnected,/upgrade,checkData,reagentSurplus,reagentMainCurve,CaliData,consumables,fault,qualityData,GPSInfo,ProjectInfo
  connectTimeOut: 3000

resource: D:\\rmyPlatform\\TestExcelAndCsv
filePath: D:\\rmyPlatform\\TestExcelAndCsv
#filePath: C:\\Users\\Administrator\\OnlineProject\\RMY\\database
##eureka配置，自为客户端，将自己注册到eureka服务器中
#eureka:
#  client:
#    register-with-eureka: true #表示是否向服务端注册自己（本服务为服务端）
#    fetch-registry: true #如果为false  则表示此服务为注册中心  相反 客户端则为true
#    cn.rmy.service-url:   # 监控页面地址
#      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka
##      defaultZone: http://localhost:7001/eureka/
#  instance:
#    instance-id: faultManagement_8081
#
#redis:
#  # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
#  database: 3
#  # redis服务器地址（默认为localhost）
#  host: localhost
#  # redis端口（默认为6379）
#  port: 6379
#  # redis访问密码（默认为空）
#  password:
#  # redis连接超时时间（单位为毫秒）
#  timeout: 1000
#  # redis连接池配置
#  jedis:
#    pool:
#      # 最大可用连接数（默认为8，负数表示无限）
#      max-active: 8
#      # 最大空闲连接数（默认为8，负数表示无限）
#      max-idle: 8
#      # 最小空闲连接数（默认为0，该值只有为正数才有作用）
#      min-idle: 0
#      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
#      max-wait: -1
