server:
  port: 8086
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://rm-bp1a6r518081j0p7zuo.mysql.rds.aliyuncs.com:3306/rmy?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&serverTimezone=GMT%2B8
    username: root
    password: Rmy12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  rabbitmq:
    #    host: 101.35.107.55
    host: 120.26.38.27
    port: 5672
    #    username: tjk
    username: rmy
    password: 123456
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
 #redis
  redis:
    #服务器连接端口
    host: 121.40.104.60
    port: 6379
    #连接密码（默认为空）
    password: rmy12345
    timeout: 30000
    jedis.pool:
      max-active: 20      #连接池最大连接数（使用负值表示没有限制）
      max-wait: -1        #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10        #连接池中的最大空闲连接
      min-idle: 0         #连接池中的最小空闲连接


  #    virtual-host: /rmy
mqtt:
  #  address: tcp://101.35.107.55:1883
  address: tcp://120.26.38.27:1883
  clientId: host_cali
  userName: admin
  password: public
  defaultTopic: /tjk,$SYS/brokers/+/clients/+/connected,$SYS/brokers/+/clients/+/disconnected,/upgrade,checkData,reagentSurplus,reagentMainCurve,CaliData,consumables,fault,qualityData,GPSInfo,ProjectInfo
  connectTimeOut: 3000


rabbit:
  queues: rmy.queue.first,rmy.queue.send,rmy.queue.connect,rmy.queue.upgrade,rmy.queue.checkData,rmy.queue.reagentSurplus,rmy.queue.reagentMainCurve,rmy.queue.CaliData,rmy.queue.consumables,rmy.queue.fault,rmy.queue.qualityData,rmy.queue.GPSInfo,rmy.queue.ProjectInfo
  exchange: rmyDirectExchange
  topicbindqueue:
    /upgrade: rmy.queue.upgrade
    /tjk: rmy.queue.first
    checkData: rmy.queue.checkData
    reagentSurplus: rmy.queue.reagentSurplus
    reagentMainCurve: rmy.queue.reagentMainCurve
    CaliData: rmy.queue.CaliData
    consumables: rmy.queue.consumables
    fault: rmy.queue.fault
    qualityData: rmy.queue.qualityData
    GPSInfo: rmy.queue.GPSInfo
    ProjectInfo: rmy.queue.ProjectInfo

filePath: C:\\Users\\Administrator\\OnlineProject\\RMY\\database\\upgradeFiles\\

oss:
  # oss 上传回调地址
  # 本地测试推荐工具 ngrok 将本地服务暴露在互联网中
  bucket: test-rmy
  endpoint: https://oss-cn-beijing.aliyuncs.com
  access-id: LTAI5t6VUDRTVkWzG2Ck5hCQ
  access-key: oSS7Ga4DlX0EuOAXQ9a6Dx2AvPmpUW
  host: https://test-rmy.oss-cn-beijing.aliyuncs.com

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: false
  mapper-locations: classpath*:dao/*.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 逻辑未删除
      logic-not-delete-value: 0
      # 逻辑已删除
      logic-delete-value: 1