server:
  port: 443
  ssl:
    key-alias: alias
    key-store-password: bpyL5983
    key-store-type: PKCS12
    key-store: classpath:7541198_cloud.realmindbio.com.pfx
  #开启gzip
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,application/vnd.yamaha.hv-script,text/css
spring:
  datasource:
    url: jdbc:mysql://rm-bp1a6r518081j0p7zuo.mysql.rds.aliyuncs.com:3306/rmy-ssl?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&serverTimezone=GMT%2B8
    username: root
    password: Rmy12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  rabbitmq:
    #    host: 101.35.107.55
    host: 120.26.38.27
    port: 5672
    #    username: tjk
    username: rmy
    password: 123456
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
  #    virtual-host: /rmy
  redis:
    #服务器连接端口
    host: 121.40.104.60
    port: 6379
    #连接密码（默认为空）
    password: rmy12345


dbNames: rmy
dbFilePath: C:\\Users\\Administrator\\Desktop\\file\\db\\
hostIp: 127.0.0.1
resource: C:\\Users\\Administrator\\Desktop\\file\\
imgPath: C:\\Users\\Administrator\\Desktop\\file\\pic\\
filePath: C:\Users\chu\Desktop\file
effectiveDuration: 30
#路径最后的双斜杠一定不能丢

oss:
  # oss 上传回调地址
  # 本地测试推荐工具 ngrok 将本地服务暴露在互联网中
  bucket: test-rmy
  endpoint: https://oss-cn-beijing.aliyuncs.com
  access-id: LTAI5t6VUDRTVkWzG2Ck5hCQ
  access-key: oSS7Ga4DlX0EuOAXQ9a6Dx2AvPmpUW
  host: https://test-rmy.oss-cn-beijing.aliyuncs.com
  callback-url: http://106.14.97.123/examination-admin-api/token/callback

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: false
  mapper-locations: classpath*:dao/*.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 逻辑未删除
      logic-not-delete-value: 0
      # 逻辑已删除
      logic-delete-value: 1